#include<iostream>
using namespace std;
int main()
{
	cout<<"hello world"<<endl;
}



//history
// c programming ->1972(AT & T BELL LABS) BY DENNIS RICHIE
// IT IS USED TO CREATE LINUX OPERATING SYSTEM
// C PROGRAMMING ->EFFICIENT AND POWERFULL


// B .STRUSTRUP->DESIGN SIMULATOR IN AT & T BELL LABS

// HE LEARN SIMULA1 AND SIMULA67
// SIMULA1 ->IT IS A FIRST OOPS LANG.

// SMALL/MEDIUM->C 
// LARGE->OBJECT ORIENTED PROGRAMMING LANGUAGE

// SIMULA1/SIMULA67->NOT EFFICIENT NOT POWERFULL

// FIRST TIME ->C + OOPS FEATURE--->C WITH CLASSES

//C++ FEATURES
// ->OBJECT ORIENTED CONCEPT
// ->C++ IS A SUPERSET OF C LANGUAGE 
// ->CONSOLED BASED APPLICATION

// S/W:
// 1 PROCEDURE ORIENTED-> C LANGAUGE
// 2 OBJECT ORIENTED ->C++ LANGUAGE


